.TL
Resume
.AU
Luiz Gustavo Ceraso Filho
.AU
https://lgceraso.netlify.app
.NH
General Skills
.PP
Basic hardware knowledge and experienced Linux user
.NH
Technical Skills
.NH 2
Languages
.NH 3
Programing
.PP
C and C++
.NH 3
Markup
.PP
LaTeX, XML, HTML, CSS and Groff
.NH 3
Scripting
.PP
Python, Ruby, JavaScript and Shell
.NH 2
Multimedia
.NH 3
Image
.PP
GIMP and ImageMagick
.NH 3
Video
.PP
FFmpeg and Kdenlive
.NH 3
Audio
.PP
Audacity
